name: HotUpdateService
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  mysql1: ^0.19.2
  dio: ^4.0.4
  meta: ">=1.3.0 <2.0.0"
  mime: ^1.0.0
  jaguar_jwt: ^3.0.0
  logging: ^1.0.2
  simple_mysql_orm: ^1.3.2
  process_run: ^0.12.3+2

